---
# tasks file for logrotate

- name: Execute role tasks
  block:

    - name: Include assert.yml
      ansible.builtin.include_tasks: assert.yml
    
    - name: Include logrotate.yml
      ansible.builtin.include_tasks: logrotate.yml

  become: yes
